apiVersion: apps/v1
kind: Deployment
metadata:
  name: "erxes"
spec:
  selector:
    matchLabels:
      app: "erxes"
  replicas: 1  
  template:  
    metadata:
      labels:
        app: "erxes"
    spec:
      containers:
      - name: "erxes"
        image: "github.com/erxes/erxes"
        ports:
        - containerPort: 80
---
